### ISSUE TITLE
medir proyecto con SonarQube

### ISSUE THREAD

**Issue by aus0006** [aus0006/GESPRO_Practicas#2]
SonarQube permitirá la medición de nuestro proyecto.
Para ello descaragaremos la herramienta desde http://www.sonarqube.org/.

**Comment by amm0131** [comment]
Con SonarQube Scanner he podido medir correctamente distintos proyectos en diferentes lenguajes .
He podido medir un proyecto en Maven pero no un proyecto desde un repositorio de Github / Bitbucket

**Comment by aus0006** [comment]
Podrías intentar hacer esto es a través de un servidor de integración continua ejecutandose el análisis del proyecto contra la instancia de SonarQube.
También clonando el repositorio en una máquina local y ejecutando el análisis, podría ser otra opción.
Aquí hay mas información:  http://sonarqube-archive.15.x6.nabble.com/simple-integration-of-sonarQube-with-just-svn-td5017436.html#a5017442
