### ISSUE TITLE
documentaciones adicionales

### ISSUE THREAD

**Issue by aus0006** [aus0006/GESPRO_Practicas#4]
Documentacion sobre OpenShift
Se debe entender el funcionamiento de la plataforma y como poder desplegar una instancia de SonarQube.

**Comment by jrb0043** [comment]
Voy a utilizar la informacion de los siguientes enlaces:

[https://developers.openshift.com/index.html](url)
y
[https://docs.openshift.org/latest/welcome/index.html](url)

**Comment by aus0006** [comment]
se podria desplegar la instancia remota de sonar cube en la plataforma OpenShift utilizando las  herramientas de cliente que proporciona OpenShift (ver enlace).

**Comment by jrb0043** [comment]
Para poder instalar las herramientas de OpenShift (rhc) en Windows, previamente ha sido necesario instalar Ruby y Git, tal y como se indica en esta guía. Según la guía deben instalar las últimas versiones disponibles tanto de Ruby(http://rubyinstaller.org/), como de Git(https://git-scm.com/). Sin embargo, al instalar las últimas versiones, se producían los siguientes errores en el funcionamiento de las herramientas rhc:
Tras instalar rhc (comando gem install rhc), se producía error cuando se intentaba configurar las herramientas con el comando rhc setup. Este error se ha solucionando probando versiones anteriores de Ruby.

Durante la configuración de rhc se producía un aviso, indicando que no ha sido posible verificar la instalación de Git. Sin embargo, Git se encontraba instalado en la máquina. Este problema no permitía clonar automaticamente el repositorio de la aplicación después de crearla con el comando rhc app-create. También, debido a que rhc no localizaba la instalación de Git, no era posible acceder de forma remota a la aplicación mediante ssh (comando rhc ssh <nombre_app>).

**Comment by aus0006** [comment]
He intentado buscar soluciones a estos problemas, aparentemente comunes, en varios foros y sno he encontrado una solución particular.
He decidido utilizar las versiones de Ruby y Git especificadas en la guía arriba indicada.
Utilizando estas versiones se han podido solucionar los problemas anteriores:
Ruby 1.9.3-p550: http://rubyinstaller.org/downloads/archives
Git 1.9.4: https://github.com/msysgit/msysgit/releases/tag/Git-1.9.4-preview20140929
