### ISSUE TITLE
Conceptos teróricos

### ISSUE THREAD

**Issue by amm0131** [aus0006/GESPRO_Practicas#5]
Se va a revisar:
-Calidad del software
-Medidas del código
Se va a utilizar la referencia de medición para la gestión de ingeniería del software

**Comment by jrb0043** [comment]
He utilizado herramientas de calidad del software que indica que el codigo esta bien y referente a las medidas de codigo se considera que hay demasiadas lineas

**Comment by amm0131** [comment]
Entendido, revisaré el código para ver si puedo reducir su tamaño
