### ISSUE TITLE
crear tarbajos relaccionados con memoria

### ISSUE THREAD

**Issue by aus0006** [aus0006/GESPRO_Practicas#9]
Para ello deberemos comparar a nivel funcional con OpenHub https://www.openhub.net/ , añadiendo una tabla comparativa.

**Comment by amm0131** [comment]
Ya he realizado el apartado "trabajos relacionados de la memoria"

**Comment by aus0006** [comment]
Podríamos añadir un anexo con el manual del administrador.
Consistiría en crear un manual del administrador con la parte de instalación y despliegue de la instancia de SonarQube, descrita en el manual de usuario. Incluir una descripción de las configuraciones realizadas.

**Comment by jrb0043** [comment]
He creado el anexo Manual del Administrador en el que explico como configurar los ficheros de SonarQube y donde se despliega la instancia en la plataforma OpenShift
